language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower web-component-tester
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: o5vjh+7zQHufCwwXdupYBai2GGcdTz1kFbdpmjeASx/rWuI4EonjaQxM39yBqcjoe201IVXnX/YgFpKuTrdtvRsGCpE+XL2SnSc8oV/9THPZ4ZlPwzpSlBDNGfvXEoxmOv15yKk+7cjm9jaiCxQG/CH6vUdew9vX6Vb51vffQBgA9fQUH+FhgNzqTIz7llikzj80GyCgHVUufu4yDOLS5iAEhhpiZgTT1M+uHrf8ysYb+yOJKofnay75BAhTJXeHSrrUg58eexPPvEgQeSfCBhi8vN4PbrXvPEX1JQ8wohQDtQ7K6heVL3ZSW44hCEJB2FGgzPItJWNZdIqSrf1K62ysKv3Gx8mtiMsUA3fogNiw/1sgroIPNb97aZ3CEBrYD2V0m71OoktonX1FvWaF5Pvcce/vPBd8AJcygO/3XXKTHVUgga/px0m5lTQItUjZIzKxj0d+YBpkV9XfrvGxwI0I+Tamifp1eGL5/7UDsNf6fxsUv85hFBNiogdln6XFFbcMHoOAqzAgXaqGEsV+DfaqEnGPn3lxMQhHQC87pDNlit4AfIdC7sR4y2DIAVKGU1056zEiz+IGnqCV1dPepg2dFjAFT1qIIlHL8Hw1N8ERo0A+nxucUL1LIFeG558b+ixBNe451dkdF4DlkwTOqRohNUIJ5zHE7bRd3Q4Icu0=
  - secure: HobxyOaiDmLBVxCwZJfdj2+tGw0kvLuJjYfZp4xAsEMYejXinlGh/MDjSVvUyGL+2hp+TRcZixaKwThV6mR/pLa2PIj//FiIPkb+6LLybyHGLd3omJqZZO5VqHQK4PVLXqWFRZr2XFivGVWAa7WEii6VMEs4EBwYq2U5z0dq9KhZWBxQNKFzCGcY+t0YUidbqPqf2OZnlngW5OYI+o4+5ftTIKDPLU7mER9OxoeeSEQjbV5EtQbpCrSc1/ZMHUDazeX5PGLUC5b9aYs0U7Gu8x7Mf9f7sDn5mbhAN/qiCVLCmbf0FdUyGc/gCTFdtPmFHztywdPG7n8Q52ruR4urPE2CZ/yyGsEbI6XEM3YfqxBai8novqnuZ10G6n4q4ovefxXk3l8c7jacgQJuTLdlRIi9L1+tQ07gSkaDISTmu0NiprQKz7Bz0FnfGgiOpfSq313NpPlY+I5s/YWdasulMXn5470zYqNaC3iYRnapKESjgF943al3oUz5wgEga/bSMUzICg2PZbgLigU4Ub570/DCbEHZqZRVEi1ADxlDP223z7XmZvlhEpWXWJ4SiZ03uPxwa+eGfT66+JT04HzDY2aWAg4qs64yHVG1nqyGmr/NT5LGWlqF3uRX1VRiOJoV0dbe2KcFU5ZkR5v0xCQnc5/IfQ4WP5nZitg4o2Sy0fE=
